version: 2
jobs:
  build:
    working_directory: ~/project/platforms/android
    docker:
      - image: circleci/android:api-25-alpha
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum "CordovaLib/build.gradle" }}
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
          - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum "CordovaLib/build.gradle" }}
      - run:
          name: Build ARR
          command: ./gradlew assembleRelease
      - run: |
          mkdir libs
          mv ~/project/platforms/android/CordovaLib/build/outputs/aar/CordovaLib-release.aar libs/libgcmvpcordova.aar
          mv ~/project/platforms/android/app/build/outputs/aar/app-release.arr libs/libgcmvp.aar
      - store_artifacts:
          path: libs